# Generated by Django 2.2.4 on 2021-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210513_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='codestudent',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='urlattend',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='urlavatar',
            field=models.TextField(default='', null=True),
        ),
    ]
