# Generated by Django 2.2.4 on 2021-05-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210524_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Embedd',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='absent',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total',
        ),
        migrations.RemoveField(
            model_name='student',
            name='urlattend',
        ),
        migrations.AddField(
            model_name='attendance',
            name='urlattend',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Schedule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='urlavatar',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
